runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'gs://your-bucket-name/onlinesalesdev-2a3972a88a4b.json'

instance_class: F2

handlers:
  - url: /static
    static_dir: static/
  - url: /download
    script: auto
  - url: /remove-background
    script: auto
  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.65